
  - name: Create Jenkins data dir
    file:
      path: /data/jenkins
      state: directory
      owner: 1000
      group: 1000
    become: true

  - name: Stop Jenkins container
    docker_service:
      project_src: docker
      state: absent

  - name: Start Jenkins container
    docker_service:
      project_src: docker
      state: present
