
  - name: Create Jenkins data dir
    file:
      path: /data/jenkins
      state: directory
      owner: 1000
      group: 1000
    become_method: sudo

  - name: Create docker-compose dir
    file:
      path: /usr/share/jenkins-docker/
      state: directory
    become_method: sudo

  - name: Copy docker-compose.yml
    copy:
      src: docker/docker-compose.yml
      dest: /usr/share/jenkins-docker/

  - name: Start Jenkins container
    command: docker-compose up
    args:
      chdir: /usr/share/jenkins-docker/

